spring.application.name=moattravel

spring.datasource.username=root

spring.datasource.password=hide0722

spring.datasource.drive-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.encoding=UTF-8

spring.sql.init.mode=always